### PR TITLE
Fixing the dev-build

### PR DESCRIPTION
**Pull request by sreerajkksd**

### CODE REVIEW

**Comment by sreerajkksd** [comment]
Provided some instructions on how to setup the dev environment. We can add more details there.

How do I actually start the build `dotstow` ? I need to add that as well.

**Comment by sreerajkksd** [comment]
package mentioned for prettier in package.json doesn't exists now. So, I took the latest one.

We should also upgrade the deprecated js libraries. I'll create a separate PR for that once I have my dev setup functional.

```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
```

**Comment by sreerajkksd** [comment]
@codejamninja let me your thoughts.

**Comment by sreerajkksd** [comment]
@codejamninja Can you approve this code if it looks fine ?

**Comment by clayrisser** [comment]
@sreerajkksd looks great. Thanks

**Pull request merged**
